name: Deploy to EC2

on:
  push:
    branches:
      - develop
  workflow_dispatch: # 手動実行も可能にする

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy to EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOYSERVERSECRET }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 57.180.91.172 >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@57.180.91.172 << 'EOF'
            cd /home/ec2-user/wiki
            git fetch origin
            git reset --hard origin/develop
            git pull origin develop
            yarn install --frozen-lockfile
            yarn build
            sudo systemctl reload httpd
          EOF
